[2023-09-03T11:18:16.832+0000] {processor.py:154} INFO - Started process (PID=403) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:18:16.874+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:18:16.890+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:18:16.890+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:18:17.134+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:18:18.058+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 1.334 seconds
[2023-09-03T11:18:49.081+0000] {processor.py:154} INFO - Started process (PID=427) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:18:49.110+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:18:49.118+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:18:49.118+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:18:49.917+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:18:53.120+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 4.095 seconds
[2023-09-03T11:19:23.798+0000] {processor.py:154} INFO - Started process (PID=451) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:19:23.837+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:19:23.872+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:19:23.854+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:19:24.666+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:19:25.881+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 2.135 seconds
[2023-09-03T11:19:56.237+0000] {processor.py:154} INFO - Started process (PID=469) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:19:56.240+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:19:56.241+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:19:56.241+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:19:56.253+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:19:56.294+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 0.062 seconds
[2023-09-03T11:20:33.803+0000] {processor.py:154} INFO - Started process (PID=492) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:20:33.822+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:20:33.827+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:20:33.827+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:20:34.107+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:20:34.537+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 0.864 seconds
[2023-09-03T11:21:04.967+0000] {processor.py:154} INFO - Started process (PID=510) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:21:04.976+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:21:04.978+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:21:04.978+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:21:05.066+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:21:05.182+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 0.252 seconds
[2023-09-03T11:21:19.806+0000] {processor.py:154} INFO - Started process (PID=523) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:21:19.851+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:21:19.872+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:21:19.872+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:21:20.695+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:21:20.098+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:21:20.752+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:21:21.200+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 1.521 seconds
[2023-09-03T11:21:51.825+0000] {processor.py:154} INFO - Started process (PID=539) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:21:51.826+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:21:51.827+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:21:51.827+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:21:51.849+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:21:51.845+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:21:51.851+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:21:51.889+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 0.068 seconds
[2023-09-03T11:22:31.425+0000] {processor.py:154} INFO - Started process (PID=564) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:22:31.491+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:22:31.540+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:22:31.500+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:22:31.853+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:22:31.786+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:22:31.861+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:22:32.220+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 0.814 seconds
[2023-09-03T11:23:03.286+0000] {processor.py:154} INFO - Started process (PID=591) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:23:03.294+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:23:03.307+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:23:03.307+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:23:03.372+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:23:03.354+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:23:03.374+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:23:03.909+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 0.631 seconds
[2023-09-03T11:23:35.712+0000] {processor.py:154} INFO - Started process (PID=610) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:23:35.755+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:23:35.775+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:23:35.775+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:23:36.057+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:23:35.976+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:23:36.066+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:23:37.527+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 1.886 seconds
[2023-09-03T11:24:08.786+0000] {processor.py:154} INFO - Started process (PID=629) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:24:08.823+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:24:08.829+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:24:08.826+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:24:09.053+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:24:09.023+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:24:09.063+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:24:09.851+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 1.091 seconds
[2023-09-03T11:24:42.500+0000] {processor.py:154} INFO - Started process (PID=654) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:24:42.516+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:24:42.533+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:24:42.533+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:24:42.601+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:24:42.588+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:24:42.606+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:24:42.803+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 0.335 seconds
[2023-09-03T11:25:16.649+0000] {processor.py:154} INFO - Started process (PID=672) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:25:16.686+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:25:16.715+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:25:16.714+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:25:17.073+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:25:17.029+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:25:17.088+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:25:20.377+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 3.884 seconds
[2023-09-03T11:25:51.236+0000] {processor.py:154} INFO - Started process (PID=698) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:25:51.248+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:25:51.262+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:25:51.261+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:25:52.049+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:25:52.019+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:25:52.065+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:25:52.641+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 1.413 seconds
[2023-09-03T11:26:22.968+0000] {processor.py:154} INFO - Started process (PID=715) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:26:22.972+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:26:22.973+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:26:22.973+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:26:22.999+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:26:22.986+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:26:23.001+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:26:23.073+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 0.115 seconds
[2023-09-03T11:26:55.817+0000] {processor.py:154} INFO - Started process (PID=741) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:26:55.819+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:26:55.821+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:26:55.820+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:26:55.858+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:26:55.856+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:26:55.860+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:26:55.984+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 0.198 seconds
[2023-09-03T11:27:29.161+0000] {processor.py:154} INFO - Started process (PID=756) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:27:29.178+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:27:29.180+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:27:29.180+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:27:29.261+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:27:29.247+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:27:29.264+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:27:30.086+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 0.963 seconds
[2023-09-03T11:28:16.426+0000] {processor.py:154} INFO - Started process (PID=772) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:28:16.481+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:28:16.525+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:28:16.494+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:28:16.891+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:28:16.851+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:28:16.896+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:28:18.568+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 3.308 seconds
[2023-09-03T11:29:15.326+0000] {processor.py:154} INFO - Started process (PID=806) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:29:15.357+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:29:15.366+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:29:15.366+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:29:15.641+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:29:15.637+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:29:15.663+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:29:15.871+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 0.739 seconds
[2023-09-03T11:29:56.449+0000] {processor.py:154} INFO - Started process (PID=824) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:29:57.205+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:29:57.237+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:29:57.234+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:29:57.441+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:29:57.362+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:29:57.448+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:29:59.052+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 2.682 seconds
[2023-09-03T11:30:37.277+0000] {processor.py:154} INFO - Started process (PID=848) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:30:37.323+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:30:37.333+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:30:37.333+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:30:37.640+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:30:37.604+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:30:37.651+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:30:38.222+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 0.994 seconds
[2023-09-03T11:31:31.122+0000] {processor.py:154} INFO - Started process (PID=877) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:31:31.147+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:31:31.154+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:31:31.154+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:31:31.269+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:31:31.245+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:31:31.288+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:31:35.755+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 4.692 seconds
[2023-09-03T11:31:59.247+0000] {processor.py:154} INFO - Started process (PID=895) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:31:59.268+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:31:59.287+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:31:59.286+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:31:59.670+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:31:59.586+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_downloads.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:31:59.709+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:32:05.674+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 6.515 seconds
[2023-09-03T11:32:26.978+0000] {processor.py:154} INFO - Started process (PID=904) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:32:27.011+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:32:27.037+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:32:27.037+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:32:27.086+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:32:27.080+0000] {dagbag.py:319} INFO - File /opt/airflow/dags/groups/group_downloads.py assumed to contain no DAGs. Skipping.
[2023-09-03T11:32:27.095+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:32:27.787+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 1.028 seconds
[2023-09-03T11:32:59.637+0000] {processor.py:154} INFO - Started process (PID=924) to work on /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:32:59.649+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_downloads.py for tasks to queue
[2023-09-03T11:32:59.662+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:32:59.662+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:32:59.682+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:32:59.680+0000] {dagbag.py:319} INFO - File /opt/airflow/dags/groups/group_downloads.py assumed to contain no DAGs. Skipping.
[2023-09-03T11:32:59.706+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_downloads.py
[2023-09-03T11:32:59.867+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_downloads.py took 0.309 seconds
