[2023-09-03T11:18:15.437+0000] {processor.py:154} INFO - Started process (PID=402) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:18:15.492+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:18:15.526+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:18:15.525+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:18:15.639+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:18:15.721+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.360 seconds
[2023-09-03T11:18:46.779+0000] {processor.py:154} INFO - Started process (PID=426) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:18:46.802+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:18:46.812+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:18:46.811+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:18:46.899+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:18:47.623+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.881 seconds
[2023-09-03T11:19:00.700+0000] {processor.py:154} INFO - Started process (PID=439) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:19:00.711+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:19:00.718+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:19:00.718+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:19:00.768+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:19:00.761+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:19:00.774+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:19:00.940+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.256 seconds
[2023-09-03T11:19:45.674+0000] {processor.py:154} INFO - Started process (PID=464) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:19:45.695+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:19:45.696+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:19:45.696+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:19:45.873+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:19:45.815+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:19:45.925+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:19:46.302+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.726 seconds
[2023-09-03T11:20:16.654+0000] {processor.py:154} INFO - Started process (PID=482) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:20:16.669+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:20:16.688+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:20:16.680+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:20:17.817+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:20:16.811+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:20:17.863+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:20:18.834+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 2.245 seconds
[2023-09-03T11:20:50.014+0000] {processor.py:154} INFO - Started process (PID=498) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:20:50.017+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:20:50.021+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:20:50.020+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:20:50.082+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:20:50.076+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:20:50.084+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:20:50.163+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.185 seconds
[2023-09-03T11:21:21.621+0000] {processor.py:154} INFO - Started process (PID=524) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:21:22.034+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:21:22.049+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:21:22.049+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:21:22.285+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:21:22.233+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:21:22.292+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:21:22.693+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 1.170 seconds
[2023-09-03T11:21:52.833+0000] {processor.py:154} INFO - Started process (PID=540) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:21:52.834+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:21:52.835+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:21:52.834+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:21:52.841+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:21:52.840+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:21:52.841+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:21:52.868+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.038 seconds
[2023-09-03T11:22:32.741+0000] {processor.py:154} INFO - Started process (PID=565) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:22:32.777+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:22:32.792+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:22:32.792+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:22:32.916+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:22:32.887+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:22:32.928+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:22:33.172+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.607 seconds
[2023-09-03T11:23:03.303+0000] {processor.py:154} INFO - Started process (PID=592) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:23:03.310+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:23:03.314+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:23:03.313+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:23:03.376+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:23:03.359+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:23:03.390+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:23:03.909+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.624 seconds
[2023-09-03T11:23:38.033+0000] {processor.py:154} INFO - Started process (PID=611) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:23:38.060+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:23:38.085+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:23:38.085+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:23:38.412+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:23:38.313+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:23:38.473+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:23:40.894+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 2.931 seconds
[2023-09-03T11:24:11.486+0000] {processor.py:154} INFO - Started process (PID=637) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:24:11.512+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:24:11.521+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:24:11.521+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:24:11.822+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:24:11.757+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:24:11.831+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:24:12.507+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 1.110 seconds
[2023-09-03T11:24:42.981+0000] {processor.py:154} INFO - Started process (PID=655) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:24:42.991+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:24:42.996+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:24:42.996+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:24:43.058+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:24:43.051+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:24:43.061+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:24:43.147+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.194 seconds
[2023-09-03T11:24:45.404+0000] {processor.py:154} INFO - Started process (PID=658) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:24:45.412+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:24:45.421+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:24:45.420+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:24:45.503+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:24:45.474+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:24:45.508+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:24:45.680+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.333 seconds
[2023-09-03T11:25:20.631+0000] {processor.py:154} INFO - Started process (PID=673) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:25:20.658+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:25:20.664+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:25:20.663+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:25:20.740+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:25:20.724+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:25:20.746+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:25:20.905+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.303 seconds
[2023-09-03T11:25:51.219+0000] {processor.py:154} INFO - Started process (PID=697) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:25:51.259+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:25:51.301+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:25:51.297+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:25:52.035+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:25:52.014+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:25:52.049+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:25:52.943+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 1.746 seconds
[2023-09-03T11:26:23.150+0000] {processor.py:154} INFO - Started process (PID=716) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:26:23.157+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:26:23.165+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:26:23.164+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:26:23.178+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:26:23.177+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:26:23.179+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:26:23.215+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.069 seconds
[2023-09-03T11:26:55.128+0000] {processor.py:154} INFO - Started process (PID=737) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:26:55.155+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:26:55.166+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:26:55.166+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:26:55.319+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:26:55.301+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:26:55.326+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:26:55.519+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.461 seconds
[2023-09-03T11:27:27.087+0000] {processor.py:154} INFO - Started process (PID=755) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:27:27.092+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:27:27.141+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:27:27.140+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:27:27.625+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:27:27.594+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:27:27.633+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:27:28.767+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 2.265 seconds
[2023-09-03T11:28:11.920+0000] {processor.py:154} INFO - Started process (PID=771) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:28:12.043+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:28:12.050+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:28:12.049+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:28:13.755+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:28:13.570+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:28:13.768+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:28:14.752+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 3.148 seconds
[2023-09-03T11:29:03.759+0000] {processor.py:154} INFO - Started process (PID=796) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:29:03.928+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:29:03.957+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:29:03.951+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:29:04.502+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:29:04.310+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:29:04.563+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:29:13.877+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 10.846 seconds
[2023-09-03T11:29:45.469+0000] {processor.py:154} INFO - Started process (PID=821) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:29:45.502+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:29:45.517+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:29:45.517+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:29:47.039+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:29:46.174+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:29:47.334+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:29:52.498+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 6.771 seconds
[2023-09-03T11:30:24.758+0000] {processor.py:154} INFO - Started process (PID=841) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:30:25.194+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:30:25.625+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:30:25.572+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:30:26.766+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:30:26.576+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:30:26.803+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:30:36.669+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 12.780 seconds
[2023-09-03T11:31:30.428+0000] {processor.py:154} INFO - Started process (PID=874) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:31:30.448+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:31:30.470+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:31:30.465+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:31:30.667+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:31:30.613+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/groups/group_transforms.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/groups/group_transforms.py", line 3, in <module>
    from airflow.utils.task_group import TaksGroup
ImportError: cannot import name 'TaksGroup' from 'airflow.utils.task_group' (/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py)
[2023-09-03T11:31:30.669+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:31:30.891+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.490 seconds
[2023-09-03T11:32:30.794+0000] {processor.py:154} INFO - Started process (PID=906) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:32:31.220+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:32:31.844+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:32:31.407+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:32:33.312+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:32:33.198+0000] {dagbag.py:319} INFO - File /opt/airflow/dags/groups/group_transforms.py assumed to contain no DAGs. Skipping.
[2023-09-03T11:32:33.397+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:32:35.226+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 4.979 seconds
[2023-09-03T11:33:05.839+0000] {processor.py:154} INFO - Started process (PID=926) to work on /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:33:05.882+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/groups/group_transforms.py for tasks to queue
[2023-09-03T11:33:05.893+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:33:05.893+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:33:05.918+0000] {logging_mixin.py:120} INFO - [2023-09-03T11:33:05.917+0000] {dagbag.py:319} INFO - File /opt/airflow/dags/groups/group_transforms.py assumed to contain no DAGs. Skipping.
[2023-09-03T11:33:05.919+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/groups/group_transforms.py
[2023-09-03T11:33:06.316+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/groups/group_transforms.py took 0.506 seconds
